#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://localhost:3306/qk # 数据库连接地址
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
  servlet:
    multipart:
      max-file-size: 10MB #单个文件最大10MB
      max-request-size: 100MB #请求总大小最大100MB
#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#mybatis配置
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis日志输出
#    map-underscore-to-camel-case: true    # 开启驼峰命名映射
#  mapper-locations: classpath:mapper/*.xml   # mapper映射文件位置

#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis日志输出
    map-underscore-to-camel-case: true # 开启驼峰命名映射
  mapper-locations: mapper/*.xml # mapper映射文件位置
  global-config:
    db-config:
      id-type: auto # 主键自动增长

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: lining-qk
    region: cn-hangzhou